# ByteBlaze config file via .yml
# Version 5.0.0
# You can use ${} to pass an enviroment varible from .env file
# Eg:
# something: ${DATA}

bot:
  TOKEN: "MTIwNzcwNDYyMjExMDYwOTQ5OA.GjpwLx.ZwyzOszygNgOwftbzuVawNttG9ikhmcq35sI80"
  EMBED_COLOR: "#115ff6"
  OWNER_ID: "991642077639221280"
  LANGUAGE: "en" # You can set it to en, vi...
  LIMIT_TRACK: 50 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 20 # The number of playlist you want to limit
  SAFE_ICONS_MODE: false # If the new icon doesn't appear, try changing this to true
  DELETE_MSG_TIMEOUT: 3000
  DEBUG_MODE: false

lavalink:
  SPOTIFY:
    # Your Spotify ID and Secret, you can get it from here: https://developer.spotify.com
    # If you don't have or don't want, you can disable it
    enable: false
    id: "db68196e6d1547d99e38629e98aec295"
    secret: "e8b32ead2ef148d1b29ba0f0e1eee310"

  # Default search suggestion for auto complete, leave it empty will use default
  AUTOCOMPLETE_SEARCH: ["spotify","yorushika", "yoasobi", "tuyu", "hinkik"]

  NP_REALTIME: false # Enable this if you want to use realtime duation in nowplaying command

  LEAVE_TIMEOUT: 60000 # The number of leave time you want

  DEFAULT_VOLUME: 100 # Must not over 1000 or bot crash

  # You can add more Lavalink servers!
  NODES:
    - url: "localhost:2333"
      name: "Asher" #only a-z A-Z 0-9 and _
      auth: "samgay"
      secure: false

    # - url: "IP:Port"
    #   name: "Name"
    #   auth: "Password"
    #   secure: false

features:
  DATABASE:
    # Note: If you enter an invalid driver, bot will use json driver as default
    driver: "json" # mongodb, mysql, json, postgres
    # Config depends on driver, you can see sample config at src/database/driver
    config: { path: "./cylane.database.json" }

  MESSAGE_CONTENT:
    enable: true
    commands:
      enable: true
      prefix: "?" # The prefix you want

  AUTOFIX_LAVALINK: # Fix the Lavalink server when the current is down
    enable: true
    reconnectTries: 5
    restTimeout: 3000

  WEB_SERVER:
    enable: false # Must enable this before using ws
    port: 3000
    websocket:
      enable: false
      host: "0.0.0.0" # Default is 0.0.0.0
      secret: "-19023454588-0934825" # You must add your secret key to use ws. A secret key is anything you want
      auth: false
      trusted: ["http://localhost:3000"]
